### PR TITLE
Making it so that forks of the project don't attempt to build and deploy from a github action when there is a push to master.

### PR DESCRIPTION
**Pull request by Sounie**
This is based on what I've seen at:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository

Disclaimer: I haven't tried this on my master branch, but will pull it down and verify it if you merge it in.

### CODE REVIEW

**Comment by OneCricketeer** [comment]
It should fail for any other fork because you wouldn't have my dockerhub password

**Comment by Sounie** [comment]
Yeah, I can confirm that the existing setup currently fails.

It looks a bit ugly and wastes processing resources though, so it would be nice if something like this could stop the action earlier.

**Review by OneCricketeer — APPROVED** [review]
Fair enough 🤷🏼

**Comment by OneCricketeer** [comment]
Ideally, only tagged commits get built, but I'm satisfied with requiring PRs to merge to master

**Comment by Sounie** [comment]
Confirming this behaves as expected. 👍

**Pull request merged**
